theme: jekyll-theme-minimal
title: Product Manager in Training
author: Daniel Gwon
email: dygwon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  pastor, pharm tech, USAF officer, SWE, MBA Candidate

# social links
twitter_username: dgwons # DO NOT include the @ character, or else the build will fail!
github_username:  dygwon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
